services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      restart: unless-stopped
      # OLLAMA_HOST: http://ollama:11434
      # OLLAMA_MODEL: ${OLLAMA_MODEL}
      # EMBEDDING_DIM: ${EMBEDDING_DIM}
      LMDB_PATH: ${LMDB_PATH}
      # QDRANT_HOST: http://qdrant:6333
    # depends_on:
    #   - ollama

  # ollama:
  #   image: ollama/ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./ollama:/root/.ollama

  # ollama-init:
  #   image: ollama/ollama
  #   depends_on:
  #     - ollama
  #   volumes:
  #     - ./ollama:/root/.ollama
  #   entrypoint: ["ollama", "pull", "${OLLAMA_MODEL}"]
  #   restart: "no"

  # qdrant:
  #   image: qdrant/qdrant:latest
  #   restart: always
  #   container_name: qdrant
  #   ports:
  #     - 6333:6333
  #     - 6334:6334
  #   environment:
  #     - QDRANT__LOG_LEVEL=INFO
  #   volumes:
  #     - ./qdrant_data:/qdrant/storage
